[package]
name = "adventofcode2018"
version = "0.1.0"
authors = ["Thomas Zumsteg <Thomas.Zumsteg@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "common"
path = "lib.rs"

[[bin]]
name = "day01"
path = "day01.rs"

[[bin]]
name = "day02"
path = "day02.rs"
